---
title: "Weather Data Preperation"
output: html_document
date: "2023-02-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## libraries

```{r}
library(httr)
library(jsonlite)
library(tidyverse)
library(stringr)
library(dplyr)
library(readr)
library(geosphere)
library(ggplot2)
library(lmtest)
library(tidysynth)
library(lubridate)
```

```{r}
readRDS("Full_Data.rds")
```



```{r}

# NO2 DD

library(dplyr)
library(estimatr)
library(modelsummary)


## Data for analysis (Only Berlin and Hamburg)
did_df <- Full_Data %>% 
  dplyr::filter(AQ_city %in% c("Berlin", "Hamburg")) %>% 
  dplyr::mutate(summer_subsidy = ifelse(AQ_date %within% lubridate::interval("2022-06-01", "2022-08-31"), 1, 0))

## Remove NAs
did_df <- did_df %>% filter(!is.na(AQ_NO2), !is.na(treatment), !is.na(after_29), !is.na(summer_subsidy), !is.na(FP_diesel_avg), !is.na(W_precipitation), !is.na(W_air_temperature), !is.na(W_wind_speed), !is.na(AQ_is_urban), !is.na(AQ_is_traffic), !is.na(station_code), !is.na(hour_of_day), !is.na(day_of_week), !is.na(calendar_week), !is.na(is_school_holiday))

## Four model specifications

# Basic Model
did_model <- estimatr::lm_robust(AQ_NO2 ~ treatment * after_29, data = did_df)

# Basic Model plus Summer Subsidy
did_model_subsidy <- estimatr::lm_robust(AQ_NO2 ~ treatment * after_29 + summer_subsidy, data = did_df)

# plus weather & Fuel prices
did_model_subsidy_weather_controls <- estimatr::lm_robust(AQ_NO2 ~ treatment * after_29 + summer_subsidy + FP_diesel_avg + W_precipitation + W_air_temperature + W_wind_speed, data = did_df)

# plus surrounding
did_model_subsidy_weather_sensor_location_controls <- estimatr::lm_robust(AQ_NO2 ~ treatment * after_29 + summer_subsidy + FP_diesel_avg + W_precipitation + W_air_temperature + W_wind_speed + AQ_is_urban + AQ_is_traffic, data = did_df)

# plus station FE
did_model_subsidy_weather_sensor_location_controls_stations <- estimatr::lm_robust(AQ_NO2 ~ treatment * after_29 + summer_subsidy + FP_diesel_avg + W_precipitation + W_air_temperature + W_wind_speed + AQ_is_urban + AQ_is_traffic + station_code, data = did_df)

# plus time FE
did_model_subsidy_weather_sensor_location_controls_stations_time <- estimatr::lm_robust(AQ_NO2 ~ treatment * after_29 + summer_subsidy + FP_diesel_avg + W_precipitation + W_air_temperature + W_wind_speed + AQ_is_urban + AQ_is_traffic + station_code + hour_of_day + day_of_week + calendar_week + is_school_holiday, data = did_df)

# no_week
did_model_subsidy_weather_sensor_location_controls_stations_time_noweek <- estimatr::lm_robust(AQ_NO2 ~ treatment * after_29 + summer_subsidy + FP_diesel_avg + W_precipitation + W_air_temperature + W_wind_speed + AQ_is_urban + AQ_is_traffic + hour_of_day + day_of_week + is_school_holiday, data = did_df)

# no Summer
did_model_all_but_Summer <- estimatr::lm_robust(AQ_NO2 ~ treatment * after_29 + FP_diesel_avg + W_precipitation + W_air_temperature + W_wind_speed + AQ_is_urban + AQ_is_traffic + hour_of_day + day_of_week + calendar_week + is_school_holiday, data = did_df)


#  no Summer & interactions
did_model_all_but_Summer_interact <- estimatr::lm_robust(AQ_NO2 ~ treatment * after_29 + FP_diesel_avg + W_precipitation + W_air_temperature + W_wind_speed + AQ_is_urban + AQ_is_traffic + hour_of_day + day_of_week + hour_of_day*day_of_week + calendar_week + day_of_week*calendar_week+ is_school_holiday, data = did_df)

## Model output
modelsummary::modelsummary(list("DiD"=did_model, 
                                "DiD (9Euro)"=did_model_subsidy,
                                "DiD (9Euro + Weather)"=did_model_subsidy_weather_controls, 
                                "DiD (9Euro + Weather + Sensor)"=did_model_subsidy_weather_sensor_location_controls,
                                "DiD (9Euro + Weather + Sensor + Stations)" = did_model_subsidy_weather_sensor_location_controls_stations,
                                "DiD (9Euro + Weather + Sensor + Stations + Time)" = did_model_subsidy_weather_sensor_location_controls_stations_time,
                                "DiD (9Euro + Weather + Sensor + Stations + Time_no_week)" =did_model_subsidy_weather_sensor_location_controls_stations_time_noweek,
                                "DiD All but summer" = did_model_all_but_Summer,
                           "DiD All but summer_interact" = did_model_all_but_Summer_interact),
                           statistic = "conf.int",
                           gof_omit="AIC|BIC|Log.Lik.",
                           fmt = 2, 
                           stars = c('*' = .05, '**' = .01, '***' = .001 ))


```



